# https://cloud.google.com/appengine/docs/the-appengine-environments#comparing_high-level_features
# https://cloud.google.com/appengine/docs/standard

runtime: java17
instance_class: F4

# https://cloud.google.com/appengine/docs/flexible/reference/app-yaml?tab=java#manual-scaling
manual_scaling:
  instances: 1
